sudo: required
dist: trusty
language: python
python:
  - "3.6"
env:
  global:
    - DEBIAN_FRONTEND=noninteractive
before_install:
  - travis_retry sudo apt-get -y --force-yes update
install:
  - pip install virtualenv
  - virtualenv env

  - source env/bin/activate

  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U Cython

  - pip install -r requirements.txt
script:
  - flake8 app
  - isort --check-only -rc app --diff
  - timeout --preserve-status 10 python -m app
cache:
  apt: true
  pip: true
notifications:
  email: false
