dist: trusty
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - flake8 --show-source app
  - isort --check-only -rc app --diff
  - timeout --preserve-status 10 python -m app
cache:
  pip: true
notifications:
  email: false
